"""
Vacuum Density Scalar Field Visualizer (Lithium-7)
--------------------------------------------------
Computes and visually renders a 2D slice of the macroscopic 
vacuum density (refractive strain) generated by the dual-shell
topological lattice of a Lithium-7 nucleus.
"""
import os
import numpy as np
import matplotlib.pyplot as plt

def compute_lithium_7_centroids(shift_distance: float = 0.85):
    """
    Returns the exact 3D coordinates and labels for the 7 nucleons 
    in the Lithium-7 cluster (Alpha Core + Outer Shell).
    """
    core_shift = shift_distance
    outer_shift = shift_distance * 2.2 
    
    return [
        # Alpha Core (2p, 2n)
        {'pos': np.array([ core_shift,  core_shift,  core_shift]), 'type': 'Core Proton',  'color': '#ff3366'},
        {'pos': np.array([-core_shift, -core_shift,  core_shift]), 'type': 'Core Proton',  'color': '#ff3366'},
        {'pos': np.array([-core_shift,  core_shift, -core_shift]), 'type': 'Core Neutron', 'color': '#00ffcc'},
        {'pos': np.array([ core_shift, -core_shift, -core_shift]), 'type': 'Core Neutron', 'color': '#00ffcc'},
        
        # Outer Shell (1p, 2n)
        {'pos': np.array([ outer_shift, -outer_shift,  outer_shift]), 'type': 'Outer Proton', 'color': '#ff99aa'},
        {'pos': np.array([-outer_shift, -outer_shift, -outer_shift]), 'type': 'Outer Neutron', 'color': '#99ffee'},
        {'pos': np.array([ outer_shift,  outer_shift, -outer_shift]), 'type': 'Outer Neutron', 'color': '#99ffee'}
    ]

def plot_density_slice(z_slice: float = 0.0, output_name: str = "lithium_7_density_slice.png"):
    nucleons = compute_lithium_7_centroids()
    
    # Expanded grid for the larger dual-shell structure
    grid_size = 400
    bound = 5.0
    x = np.linspace(-bound, bound, grid_size)
    y = np.linspace(-bound, bound, grid_size)
    X, Y = np.meshgrid(x, y)
    
    density_field = np.zeros_like(X)
    characteristic_radius = 1.0
    
    for n in nucleons:
        cx, cy, cz = n['pos']
        r_sq = (X - cx)**2 + (Y - cy)**2 + (z_slice - cz)**2
        local_density = 1.0 / (1.0 + (r_sq / (characteristic_radius**2))**2)
        density_field += local_density

    # --- Render Configuration ---
    fig, ax = plt.subplots(figsize=(10, 8))
    fig.patch.set_facecolor('#0f0f0f')
    ax.set_facecolor('#0f0f0f')
    
    cmap = plt.cm.inferno
    cmap.set_bad(color='#0f0f0f')
    
    im = ax.imshow(density_field, extent=[-bound, bound, -bound, bound], 
                   origin='lower', cmap=cmap, alpha=0.9, vmin=0.0)
                   
    # Compute Gradient Flux
    grad_y, grad_x = np.gradient(density_field)
    
    # Overlay Continuous Streamlines
    ax.streamplot(x, y, grad_x, grad_y, 
                  color='#aaaaaa', linewidth=1.2, density=1.5, 
                  arrowstyle='->', arrowsize=1.5)
                   
    # Overlay CoM markers
    for n in nucleons:
        cx, cy, cz = n['pos']
        if abs(cz - z_slice) < 2.0:
            depth_scale = np.exp(-abs(cz - z_slice) * 0.8)
            
            ax.scatter(cx, cy, color=n['color'], s=500 * depth_scale, marker='+', linewidth=3, alpha=0.8)
            ax.scatter(cx, cy, color=n['color'], s=150 * depth_scale, edgecolor=n['color'], facecolor='none', linewidth=2, alpha=0.9)
            
            ax.text(cx + 0.15, cy + 0.15, f"{n['type']}", color=n['color'], 
                    fontsize=10, fontweight='bold', alpha=0.9,
                    bbox=dict(facecolor='#111111', edgecolor='none', alpha=0.5, pad=1))

    ax.set_title(f"Vacuum Density Mapping: Lithium-7 (Slice Z={z_slice:.1f})", color='white', fontsize=16, pad=20)
    ax.set_xlabel("X (Topological Node Lengths)", color='white', fontsize=12)
    ax.set_ylabel("Y (Topological Node Lengths)", color='white', fontsize=12)
    ax.tick_params(colors='white')
    ax.grid(color='#ffffff', linestyle=':', alpha=0.2)
    
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label(r'Topological Density Strain ($\kappa_V$ Gradient)', color='white', fontsize=12)
    cbar.ax.yaxis.set_tick_params(color='white')
    cbar.ax.yaxis.set_tick_params(labelcolor='white')

    os.makedirs('tests/outputs', exist_ok=True)
    out_path = os.path.join('tests/outputs', output_name)
    plt.tight_layout()
    plt.savefig(out_path, dpi=300, facecolor=fig.get_facecolor())
    plt.close()
    
    print(f"[*] Saved Volumetric Density Slice: {out_path}")

if __name__ == "__main__":
    # The Alpha core is at Z = +/- 0.85
    # The outer shell is roughly at Z = +/- 1.87
    plot_density_slice(z_slice=0.85, output_name="lithium_7_density_core.png")
    plot_density_slice(z_slice=1.87, output_name="lithium_7_density_outer_shell.png")
    plot_density_slice(z_slice=0.0, output_name="lithium_7_density_equator.png")
