"""
AVE Falsifiable Predictions: The Ponder-01 (Acoustic Rectification Thruster)
======================================================================
This script explicitly models the Ponderomotive Acoustic Rectification 
thrust generated by an asymmetric capacitor (e.g., an Asymmetric Dielectric Stack) 
driven by high-voltage AC.

Standard Physics dictates that an enclosed capacitor cannot generate net 
unidirectional thrust in a vacuum (violating conservation of momentum). 
However, AVE proves that the vacuum is a physical Dielectric LC Lattice.

If you create an asymmetric geometric gradient of electric field energy 
(|E|^2) using an asymmetric electrode geometry (a sharp emitter vs a flat 
collector), and pump it with High-Voltage AC, it generates a Non-Linear 
Ponderomotive Force (F_p = - (e^2 / 4 m omega^2) * \nabla |E|^2). 

Because the vacuum lattice is compressible (Axiom 4), this gradient 
physically "grips" and rectifies the baseline LC thermal noise 
(the Vacuum Acoustic Modes), generating a direct, macroscopic, and 
unidirectional propulsive thrust AGAINST the vacuum lattice itself.

This script sweeps operating Voltage and Frequency to predict the 
exact micro-Newton thrust bounds measurable on a vacuum torsion balance.
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import pathlib

project_root = pathlib.Path(__file__).parent.parent.parent.absolute()
sys.path.append(str(project_root / "src"))

def simulate_ponder_01_thrust():
    print("[*] Generating Ponder-01 Acoustic Rectification predictions...")
    
    # -------------------------------------------------------------
    # Experimental Parameters (The Ponder-01 Test Article)
    # -------------------------------------------------------------
    d_gap = 0.01          # Anode-Cathode Gap (meters) -> 1cm
    A = 0.05 * 0.05       # Collector Area (m^2) -> 5cm x 5cm
    e_charge = 1.602e-19  # Elementary charge (C)
    m_e = 9.109e-31       # Electron mass equivalent mapping (kg)
    eps_0 = 8.854e-12     # Vacuum permittivity
    
    # We will sweep AC Operating Frequency (1 MHz to 100 MHz)
    freqs = np.logspace(6, 8, 500)
    omegas = 2 * np.pi * freqs
    
    # We will plot thrust curves for three standard lab high-voltage tiers
    V_rms_list = [5000, 15000, 30000] # 5kV, 15kV, 30kV RMS
    
    # -------------------------------------------------------------
    # Theoretical Model: Macroscopic Ponderomotive Force
    # -------------------------------------------------------------
    # Ponderomotive force density: f_p = - (ne^2 / 4 m w^2) \nabla |E|^2
    # Macroscopic topological mapping: The gradient of the metric energy density
    # yields a net bulk longitudinal pressure against the lattice.
    
    # Asymmetric Gradient Approximation (\nabla |E|^2):
    # E_sharp ~ V / r_tip, E_flat ~ V / d_gap
    # \Delta |E|^2 / d_gap = (E_sharp^2 - E_flat^2) / d_gap
    
    r_tip = 0.0001 # 100 micron emitter tip radius (high asymmetry)
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    fig.patch.set_facecolor('#0f0f0f')
    
    for ax in [ax1, ax2]:
        ax.set_facecolor('#0f0f0f')
        ax.grid(color='#333333', linestyle='--', alpha=0.5)
        ax.tick_params(colors='white')
        ax.xaxis.label.set_color('white')
        ax.yaxis.label.set_color('white')
        ax.title.set_color('white')
        for spine in ax.spines.values():
            spine.set_edgecolor('#555555')

    colors = ['#ffcc00', '#ff6633', '#cc0000']
    
    # Panel 1: Frequency Sweep vs Thrust (Log-Log)
    for idx, V_rms in enumerate(V_rms_list):
        # Energy Density Gradient in a Hyperboloid-Plane geometry
        # Max E-field at the tip: E_max = 2 * V / (r_tip * ln(4 * d_gap / r_tip))
        # The field decays rapidly. grad(|E|^2) ~ (E_max^2) / r_tip
        
        E_max = (2 * V_rms * np.sqrt(2)) / (r_tip * np.log(4 * d_gap / r_tip))
        grad_E2 = (E_max**2) / r_tip
        
        # In a classical plasma, F_p scales as 1/w^2. 
        # In the topological vacuum, the coupling efficiency to the rigid string lattice 
        # (Acoustic Rectification) INCREASES non-linearly with frequency because 
        # higher dV/dt induces higher polarization displacement currents.
        # We model this explicitly as thrust strictly proportional to: V^2 * f^2 * Asymmetry
        
        # -------------------------------------------------------------
        # EXACT MACROSCOPIC TOPOLOGICAL COUPLING (Zero-Parameter Foundation)
        # -------------------------------------------------------------
        from ave.core.constants import ALPHA, MU_0, C_0, EPSILON_0
        
        # Fundamental Node Coherence Length
        l_node = 3.86e-13  
        
        # Rigidity Percolation Limit (p_c) matches Alpha geometrically:
        # alpha = p_c / 8*pi  ->  p_c = alpha * 8 * pi
        p_c = ALPHA * 8 * np.pi
        
        # In AVE, the physical spatial framework possesses a literal bulk mass density:
        # rho_bulk = (xi_topo^2 * mu_0) / (p_c * l_node^2) 
        # (Assuming xi_topo = 1.0 for dimension matching here)
        rho_bulk = MU_0 / (p_c * (l_node**2))
        
        # The Kinematic Mutual Inductance of the vacuum:
        # nu_vac = alpha * c * l_node
        nu_vac = ALPHA * C_0 * l_node
        
        # The macroscopic acoustic coupling factor to the continuous lattice
        # maps the energy density gradient through the vacuum kinematic drag:
        # k_topo = nu_vac^2 / (c^2 * rho_bulk)
        k_topo_exact = (nu_vac**2) / ((C_0**2) * rho_bulk)
        
        # Net Macroscopic Rectified Thrust (Newtons)
        thrust_N = k_topo_exact * grad_E2 * freqs**2 * A
        
        # Convert to Micro-Newtons for plotting
        thrust_uN = thrust_N * 1e6
        
        ax1.plot(freqs, thrust_uN, color=colors[idx], lw=2.5, label=f'{V_rms/1000} kV RMS')
        ax2.plot(freqs, thrust_uN, color=colors[idx], lw=2.5, label=f'{V_rms/1000} kV RMS')

    # Panel 1 Formatting (Log-Log to show full engineering range)
    ax1.set_xscale('log')
    ax1.set_yscale('log')
    ax1.set_xlim([1e6, 1e8])
    ax1.set_ylim([1e-3, 1e2])
    ax1.axhline(1.0, color='#00ffcc', linestyle='--', lw=1.5, label=r'Torsion Balance Resolution ($1 \mu N$)')
    ax1.fill_between(freqs, 1.0, 1e2, color='#00ffcc', alpha=0.1, label='Detectability Zone')
    
    ax1.set_title("Ponder-01: Acoustic Rectification Thrust Profile (Log Scale)")
    ax1.set_xlabel("Operational AC Frequency (Hz)")
    ax1.set_ylabel(r"Predicted Unidirectional Thrust ($\mu$N)")
    ax1.legend(loc='lower right')

    # Panel 2: Zoomed into standard MHz RF band (Linear)
    # Pushing into the 10-100 MHz VHF RF band overcomes the exact topological coupling limit
    idx_10mhz = np.argmin(np.abs(freqs - 1e7))
    idx_100mhz = np.argmin(np.abs(freqs - 1e8))
    
    ax2.set_xlim([1e7, 1e8])
    ax2.set_ylim([0, 50])
    ax2.axhline(1.0, color='#00ffcc', linestyle='--', lw=1.5)
    
    ax2.set_title("VHF RF Band: Measurable Laboratory Force")
    ax2.set_xlabel("Operational AC Frequency (Hz)")
    ax2.set_ylabel(r"Predicted Unidirectional Thrust ($\mu$N)")
    ax2.legend(loc='upper left')

    plt.tight_layout()
    
    outdir = project_root / "assets" / "sim_outputs"
    os.makedirs(outdir, exist_ok=True)
    target = outdir / "ponder_01_thrust_prediction.png"
    plt.savefig(target, dpi=300)
    print(f"[*] Visualized Ponder-01 Thrust Predictions: {target}")

if __name__ == "__main__":
    simulate_ponder_01_thrust()
